spring.application.name=quimbolito
server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://shuttle.proxy.rlwy.net:27551/railway
spring.datasource.username=root
spring.datasource.password=qmixPBhYiklJWGCoPZhGbyPQglSPzcvr
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

app.jwt.secret=quimbolitos-secret-key-quimbolitos-secret-key-2026
app.jwt.expiration-ms=86400000

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=30MB

app.storage.local.enabled=${APP_STORAGE_LOCAL_ENABLED:true}
# Config local anterior relativa
# app.storage.foto-perfil-dir=storage/foto-perfil
# app.storage.recuerdos-dir=storage/recuerdos
# app.storage.peliculas-dir=storage/peliculas
# app.storage.recuerdos-mapa-dir=storage/recuerdos-mapa
# app.storage.canciones-dir=storage/canciones
# app.storage.canciones-audio-dir=storage/canciones-audio
# app.storage.visual-preguntas-dir=storage/visual-preguntas
app.storage.foto-perfil-dir=${APP_STORAGE_FOTO_PERFIL_DIR:storage/foto-perfil}
app.storage.recuerdos-dir=${APP_STORAGE_RECUERDOS_DIR:storage/recuerdos}
app.storage.peliculas-dir=${APP_STORAGE_PELICULAS_DIR:storage/peliculas}
app.storage.recuerdos-mapa-dir=${APP_STORAGE_RECUERDOS_MAPA_DIR:storage/recuerdos-mapa}
app.storage.canciones-dir=${APP_STORAGE_CANCIONES_DIR:storage/canciones}
app.storage.canciones-audio-dir=${APP_STORAGE_CANCIONES_AUDIO_DIR:storage/canciones-audio}
app.storage.visual-preguntas-dir=${APP_STORAGE_VISUAL_PREGUNTAS_DIR:storage/visual-preguntas}

app.admin.bootstrap.enabled=true
app.admin.bootstrap.nombre=Administrador
app.admin.bootstrap.alias=admin
app.admin.bootstrap.email=admin@quimbolitos.local
app.admin.bootstrap.password=${ADMIN_PASSWORDSTRAP}
app.admin.bootstrap.fecha-nacimiento=1990-01-01
app.admin.bootstrap.biografia=Administrador bootstrap local para desarrollo

cloudinary.cloud-name=dglzywho2
cloudinary.api-key=628954754319734
cloudinary.api-secret=k4BigmKy14npSHuPc_cpkwXmTQ8

supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
