spring.application.name=quimbolito
server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://shuttle.proxy.rlwy.net:27551/railway
spring.datasource.username=root
spring.datasource.password=qmixPBhYiklJWGCoPZhGbyPQglSPzcvr
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

app.jwt.secret=quimbolitos-secret-key-quimbolitos-secret-key-2026
app.jwt.expiration-ms=86400000

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=30MB

app.admin.bootstrap.enabled=true
app.admin.bootstrap.nombre=Administrador
app.admin.bootstrap.alias=admin
app.admin.bootstrap.email=admin@quimbolitos.local
app.admin.bootstrap.password=${ADMIN_PASSWORDSTRAP}
app.admin.bootstrap.fecha-nacimiento=1990-01-01
app.admin.bootstrap.biografia=Administrador bootstrap local para desarrollo

cloudinary.cloud-name=dglzywho2
cloudinary.api-key=628954754319734
cloudinary.api-secret=k4BigmKy14npSHuPc_cpkwXmTQ8

supabase.url=https://zlirjidjaylbmorluzxb.supabase.co
supabase.key=sb_secret_QXRhMKmrEwYkWQu7Y7lQAA_T5TJ-nB-
